### ISSUE TITLE
System.TimeoutException Error

### ISSUE THREAD

**Issue by ewilliams8** [EvanMulawski/FanControl.CorsairLink#112]
Hi,

Are you able to help with this error?

_2023-10-14T11:58:08.0167339Z [ERR] CORSAIR iCUE Commander CORE (d30c10905ecb3abaf8ae36f55091005f): An error occurred refreshing device 'CORSAIR iCUE Commander CORE (d30c10905ecb3abaf8ae36f55091005f)' (\\?\hid#vid_1b1c&pid_0c1c&mi_00#9&2d2dbcd9&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030})

Type: System.TimeoutException
Message: Operation timed out.
Source: HidSharp
Stack Trace:
   at HidSharp.Platform.Windows.NativeMethods.OverlappedOperation(IntPtr ioHandle, IntPtr eventHandle, Int32 eventTimeout, IntPtr closeEventHandle, Boolean overlapResult, NativeOverlapped* overlapped, UInt32& bytesTransferred)
   at HidSharp.Platform.Windows.WinHidStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at CorsairLink.Devices.CommanderCoreDevice.SendCommand(ReadOnlySpan`1 command, ReadOnlySpan`1 data, ReadOnlySpan`1 waitForDataType)
   at CorsairLink.Devices.CommanderCoreDevice.ReadFromEndpoint(ReadOnlySpan`1 endpoint, ReadOnlySpan`1 dataType)
   at CorsairLink.Devices.CommanderCoreDevice.RefreshImpl(Boolean initialize)
   at FanControl.CorsairLink.CorsairLinkPlugin.Refresh()_
   
   
   
[CorsairLink.log](https://github.com/EvanMulawski/FanControl.CorsairLink/files/12905027/CorsairLink.log)

**Comment by EvanMulawski** [comment]
This looks like a similar issue to #107, specifically an issue with the USB controller the device is connected to. Ensure your BIOS is up-to-date and try using a different USB header on your motherboard.

**Comment by ewilliams8** [comment]
Thanks for the suggestion, I'll try a different header.

I believe my BIOS is up to date but will check that too.

**Comment by ewilliams8** [comment]
Sadly updating BIOS and changing to a new header hasn't helped and I'm still getting the error.

**Comment by EvanMulawski** [comment]
Does the device work with SignalRGB or the attached build of OpenRGB?

[OpenRGB_Windows_64_6c8da3a0.zip](https://github.com/EvanMulawski/FanControl.CorsairLink/files/12910302/OpenRGB_Windows_64_6c8da3a0.zip)

**Comment by ewilliams8** [comment]
Yep, I can control it with that version of OpenRGB.

**Comment by EvanMulawski** [comment]
@ewilliams8 Please try the attached build and post the CorsairLink.log file after testing.

[FanControl.CorsairLink-Issue112-v20231015r001.zip](https://github.com/EvanMulawski/FanControl.CorsairLink/files/12910599/FanControl.CorsairLink-Issue112-v20231015r001.zip)

**Comment by ewilliams8** [comment]
Thanks for you help with this.

Latest log here - New build installed this morning (17-10-23):

[CorsairLink.2.log](https://github.com/EvanMulawski/FanControl.CorsairLink/files/12926959/CorsairLink.2.log)

**Comment by EvanMulawski** [comment]
@ewilliams8 It looks like it functions correctly for 9 minutes and then the errors start. Is that correct?

**Comment by ewilliams8** [comment]
It looks like about 14 minutes yesterday, but was only 2 mins this morning:

**2023-10-18T09:15:42**.4372578Z [INF] Plugin: Version: 1.4.1
2023-10-18T09:15:42.5063172Z [INF] HID Device Manager: Found 2 Corsair HID device(s)
  name=CORSAIR iCUE Commander CORE, devicePath=\\?\hid#vid_1b1c&pid_0c1c&mi_00#9&2d2dbcd9&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
  name=CORSAIR iCUE Commander CORE, devicePath=\\?\hid#vid_1b1c&pid_0c1c&mi_01#9&156a3094&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}

2023-10-18T09:15:42.5243328Z [INF] HID Device Manager: Found 1 supported Corsair HID device(s)
  name=CORSAIR iCUE Commander CORE, devicePath=\\?\hid#vid_1b1c&pid_0c1c&mi_00#9&2d2dbcd9&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}

2023-10-18T09:15:42.5378442Z [WRN] Device Enumeration: Failed to enumerate SiUsbXpress devices. This can be ignored if no devices require this driver.
2023-10-18T09:15:42.7605459Z [INF] Device Initialization: \\?\hid#vid_1b1c&pid_0c1c&mi_00#9&2d2dbcd9&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
2023-10-18T09:15:42.7650497Z [INF] CORSAIR iCUE Commander CORE (d30c10905ecb3abaf8ae36f55091005f): Firmware Version: 2.11.221
2023-10-18T09:15:42.7655501Z [INF] CORSAIR iCUE Commander CORE (d30c10905ecb3abaf8ae36f55091005f): Sensor: CorsairLink/\\?\hid#vid_1b1c&pid_0c1c&mi_00#9&2d2dbcd9&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}/SpeedSensor/0
2023-10-18T09:15:42.7655501Z [INF] CORSAIR iCUE Commander CORE (d30c10905ecb3abaf8ae36f55091005f): Sensor: CorsairLink/\\?\hid#vid_1b1c&pid_0c1c&mi_00#9&2d2dbcd9&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}/SpeedSensor/1
2023-10-18T09:15:42.7655501Z [INF] CORSAIR iCUE Commander CORE (d30c10905ecb3abaf8ae36f55091005f): Sensor: CorsairLink/\\?\hid#vid_1b1c&pid_0c1c&mi_00#9&2d2dbcd9&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}/SpeedSensor/2
2023-10-18T09:15:42.7655501Z [INF] CORSAIR iCUE Commander CORE (d30c10905ecb3abaf8ae36f55091005f): Sensor: CorsairLink/\\?\hid#vid_1b1c&pid_0c1c&mi_00#9&2d2dbcd9&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}/SpeedSensor/3
2023-10-18T09:15:42.7655501Z [INF] CORSAIR iCUE Commander CORE (d30c10905ecb3abaf8ae36f55091005f): Sensor: CorsairLink/\\?\hid#vid_1b1c&pid_0c1c&mi_00#9&2d2dbcd9&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}/SpeedSensor/4
2023-10-18T09:15:42.7655501Z [INF] CORSAIR iCUE Commander CORE (d30c10905ecb3abaf8ae36f55091005f): Sensor: CorsairLink/\\?\hid#vid_1b1c&pid_0c1c&mi_00#9&2d2dbcd9&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}/SpeedSensor/5
2023-10-18T09:15:42.7655501Z [INF] CORSAIR iCUE Commander CORE (d30c10905ecb3abaf8ae36f55091005f): Sensor: CorsairLink/\\?\hid#vid_1b1c&pid_0c1c&mi_00#9&2d2dbcd9&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}/SpeedSensor/6
2023-10-18T09:15:42.7665510Z [INF] CORSAIR iCUE Commander CORE (d30c10905ecb3abaf8ae36f55091005f): Sensor: CorsairLink/\\?\hid#vid_1b1c&pid_0c1c&mi_00#9&2d2dbcd9&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}/TemperatureSensor/0
2023-10-18T09:15:42.7665510Z [INF] CORSAIR iCUE Commander CORE (d30c10905ecb3abaf8ae36f55091005f): Sensor: CorsairLink/\\?\hid#vid_1b1c&pid_0c1c&mi_00#9&2d2dbcd9&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}/TemperatureSensor/1
2023-10-18T09:15:42.7670517Z [INF] CORSAIR iCUE Commander CORE (d30c10905ecb3abaf8ae36f55091005f): Controller: CorsairLink/\\?\hid#vid_1b1c&pid_0c1c&mi_00#9&2d2dbcd9&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}/SpeedController/0
2023-10-18T09:15:42.7670517Z [INF] CORSAIR iCUE Commander CORE (d30c10905ecb3abaf8ae36f55091005f): Controller: CorsairLink/\\?\hid#vid_1b1c&pid_0c1c&mi_00#9&2d2dbcd9&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}/SpeedController/1
2023-10-18T09:15:42.7670517Z [INF] CORSAIR iCUE Commander CORE (d30c10905ecb3abaf8ae36f55091005f): Controller: CorsairLink/\\?\hid#vid_1b1c&pid_0c1c&mi_00#9&2d2dbcd9&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}/SpeedController/2
2023-10-18T09:15:42.7670517Z [INF] CORSAIR iCUE Commander CORE (d30c10905ecb3abaf8ae36f55091005f): Controller: CorsairLink/\\?\hid#vid_1b1c&pid_0c1c&mi_00#9&2d2dbcd9&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}/SpeedController/3
2023-10-18T09:15:42.7670517Z [INF] CORSAIR iCUE Commander CORE (d30c10905ecb3abaf8ae36f55091005f): Controller: CorsairLink/\\?\hid#vid_1b1c&pid_0c1c&mi_00#9&2d2dbcd9&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}/SpeedController/4
2023-10-18T09:15:42.7670517Z [INF] CORSAIR iCUE Commander CORE (d30c10905ecb3abaf8ae36f55091005f): Controller: CorsairLink/\\?\hid#vid_1b1c&pid_0c1c&mi_00#9&2d2dbcd9&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}/SpeedController/5
2023-10-18T09:15:42.7670517Z [INF] CORSAIR iCUE Commander CORE (d30c10905ecb3abaf8ae36f55091005f): Controller: CorsairLink/\\?\hid#vid_1b1c&pid_0c1c&mi_00#9&2d2dbcd9&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}/SpeedController/6
**2023-10-18T09:17:20**.5075885Z [ERR] CORSAIR iCUE Commander CORE (d30c10905ecb3abaf8ae36f55091005f): An error occurred refreshing device 'CORSAIR iCUE Commander CORE (d30c10905ecb3abaf8ae36f55091005f)' (\\?\hid#vid_1b1c&pid_0c1c&mi_00#9&2d2dbcd9&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030})

**Comment by EvanMulawski** [comment]
Not sure what the issue is. Since I've only received one report of this occurring, I'm inclined to believe it's an issue specific to your system. Any other software running that might be communicating with the device?

**Comment by ewilliams8** [comment]
I agree, I’m thinking of replacing the AIO 

The only other software which potentially conflicts is OpenRGB.

**Comment by EvanMulawski** [comment]
@ewilliams8 Please try v1.4.2 and the build of OpenRGB linked in https://github.com/EvanMulawski/FanControl.CorsairLink/issues/101#issuecomment-1806536056

**Comment by jflevesque** [comment]
I just did some troubleshooting and maybe this could help. By default, I have iCue disabled on startup, same for the Corsair Service, since this causes issue with Fan Control. I've manually restart the Corsair Service, started iCue, waited until all devices were discovered, shutdown iCue, stop the Corsair Service, relaunch FanControl and my sensors were once again being discovered.

**Comment by EvanMulawski** [comment]
@jflevesque Moved to #127
