### ISSUE TITLE
Hydro Platinum communication failure

### ISSUE THREAD

**Issue by EvanMulawski** [EvanMulawski/FanControl.CorsairLink#127]
> Sorry for reopening this issue, but I've been having the same issue as of today (that I noticed anyway). This is a brand new system that I've put up on Saturday, installed the plugin in FanControl yesterday and noticed the issue this morning when waking the computer. I've tried rebooting the computer, thinking something didn't happen properly when waking, but still getting the error continuously. These are the logs when FanControl boots:

```
2023-12-04T14:36:41.2835824Z [INF] Plugin: Version: 1.4.3
2023-12-04T14:36:41.3354996Z [INF] HID Device Manager: Found 5 Corsair HID device(s)
  name=Hid Interface, devicePath=\\?\hid#vid_1b1c&pid_0a51&mi_03&col01#b&1b0a5998&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
  name=Hid Interface, devicePath=\\?\hid#vid_1b1c&pid_0a51&mi_03&col02#b&1b0a5998&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}
  name=Hid Interface, devicePath=\\?\hid#vid_1b1c&pid_0a51&mi_03&col03#b&1b0a5998&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}
  name=H150iELITE, devicePath=\\?\hid#vid_1b1c&pid_0c37#9&33b5a7ad&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
  name=CORSAIR Lighting Node CORE, devicePath=\\?\hid#vid_1b1c&pid_0c1a#9&1353aae7&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}

2023-12-04T14:36:41.3490256Z [INF] HID Device Manager: Found 1 supported Corsair HID device(s)
  name=H150iELITE, devicePath=\\?\hid#vid_1b1c&pid_0c37#9&33b5a7ad&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}

2023-12-04T14:36:41.3555413Z [WRN] Device Enumeration: Failed to enumerate SiUsbXpress devices. This can be ignored if no devices require this driver.
2023-12-04T14:36:41.3605414Z [INF] Device Initialization: \\?\hid#vid_1b1c&pid_0c37#9&33b5a7ad&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
2023-12-04T14:36:42.6915662Z [ERR] H150iELITE (DB24A21026AA8DD876BFC87183CD0E00): An error occurred refreshing device 'H150iELITE (DB24A21026AA8DD876BFC87183CD0E00)' (\\?\hid#vid_1b1c&pid_0c37#9&33b5a7ad&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030})

Type: CorsairLink.CorsairLinkDeviceException
Message: Communication failure.
Source: FanControl.CorsairLink
Stack Trace:
   at CorsairLink.Devices.HydroPlatinumDevice.SendCommand(Byte command, ReadOnlySpan`1 data)
   at CorsairLink.Devices.HydroPlatinumDevice.ReadState()
   at CorsairLink.Devices.HydroPlatinumDevice.Refresh()
   at FanControl.CorsairLink.CorsairLinkPlugin.Refresh()
Data:
    writeBuffer: 003F10FF00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF04
    readBuffer: 0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
Inner Exception:
    Type: System.ObjectDisposedException
    Message: Closed.
    Source: HidSharp
    Stack Trace:
   at HidSharp.Platform.Windows.NativeMethods.OverlappedOperation(IntPtr ioHandle, IntPtr eventHandle, Int32 eventTimeout, IntPtr closeEventHandle, Boolean overlapResult, NativeOverlapped* overlapped, UInt32& bytesTransferred)
   at HidSharp.Platform.Windows.WinHidStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at CorsairLink.Devices.HydroPlatinumDevice.WriteAndRead(Byte[] writeBuffer, Byte[] readBuffer)
   at CorsairLink.Devices.HydroPlatinumDevice.SendCommand(Byte command, ReadOnlySpan`1 data)
```

> Is there anything I can do to help troubleshoot this issue?

> I just did some troubleshooting and maybe this could help. By default, I have iCue disabled on startup, same for the Corsair Service, since this causes issue with Fan Control. I've manually restart the Corsair Service, started iCue, waited until all devices were discovered, shutdown iCue, stop the Corsair Service, relaunch FanControl and my sensors were once again being discovered.

_Originally posted by @jflevesque in https://github.com/EvanMulawski/FanControl.CorsairLink/issues/112#issuecomment-1838812577_

**Comment by EvanMulawski** [comment]
@jflevesque I'm going to need a USB packet capture when you get a chance. Please follow the steps below.

1. Install the latest version of Wireshark and install USBPcap when prompted during the installation process. 
2. Disable iCUE at startup and disable the Corsair Service service.
3. Disable Fan Control at startup (or disable this plugin).
4. Restart your PC.
5. Launch Wireshark as administrator and start a USBPcap capture.
6. Enable and start the Corsair Service service and wait one minute.
7. Launch iCUE and wait one minute.
8. Save the capture (should be a pcapng file), ZIP it, and upload it here.

Let me know if you need any additional help or information. Thanks!

**Comment by jflevesque** [comment]
I've installed Wireshark but at the moment, Fan control rediscovers the sensors after a reboot. I'll monitor the situation and if the issue comes back, I'll get you the traces.

**Comment by jflevesque** [comment]
Still haven't had the issue. I think it may have been caused when I had uninstalled Corsair Link 4 and I reinstalled when issue appeared. I suggest closing the issue.

**Comment by jflevesque** [comment]
Turns out, the issue has come back. Taking the traces now

**Comment by Profetorum** [comment]
Was happening to me apparently because i had set my hydro pump speed to go on low RPM.
Not sure that's the actual issue but now i'm not facing the error

**Comment by EvanMulawski** [comment]
@jflevesque @Profetorum Can your reproduce this if you set the pump power below a certain percent? If so, what is that percent value?

**Comment by Profetorum** [comment]
> @jflevesque @Profetorum Can your reproduce this if you set the pump power below a certain percent? If so, what is that percent value?

I tried for a bunch but i can't really replicate the issue consistently . It's very random - when i managed to catch the speeds it errored out it was 2506 RPM once and 2501 RPM another time. I'm talking about the pump speed.
Im not even sure the erroring is related to that, honestly. Sadly i can't help much more

**Comment by EvanMulawski** [comment]
Closing in favor of #80
