### ISSUE TITLE
Sensors not found after sleep

### ISSUE THREAD

**Issue by Andyden4483** [EvanMulawski/FanControl.CorsairLink#154]
Following up on issue #153 my PC went to sleep today and on wake i got the following:-

![image](https://github.com/EvanMulawski/FanControl.CorsairLink/assets/157853140/31fce6a4-bd86-426a-acc0-ef1758438313)

Icue isnt on and all corsair services stopped as per issue #153 so whats the issue? Do you need logs?

![image](https://github.com/EvanMulawski/FanControl.CorsairLink/assets/157853140/28495950-10ae-45d6-8b83-6dd8745c13c4)

**Comment by Andyden4483** [comment]
2024-02-21T11:51:22.1160481Z [ERR] Corsair H150i Pro (1C2C03043D1712AB799502138DEE93AD): An error occurred refreshing device 'Corsair H150i Pro (1C2C03043D1712AB799502138DEE93AD)' (\\?\usb#vid_1b1c&pid_0c12#7289_2.0#{3c5e1462-5695-4e18-876b-f3f3d08aaf18})

Type: CorsairLink.SiUsbXpress.Driver.SiUsbXpressDriverException
Message: Driver operation failed.
Source: FanControl.CorsairLink
Stack Trace:
   at CorsairLink.SiUsbXpress.Driver.SiUsbXpressDevice.WriteInternal(Byte[] data)
   at CorsairLink.SiUsbXpress.Driver.SiUsbXpressDevice.WriteAndRead(Byte[] buffer)
   at CorsairLink.Devices.HydroAsetekProDevice.WriteAndRead(Byte[] buffer)
   at CorsairLink.Devices.HydroAsetekProDevice.GetLiquidTemperature()
   at CorsairLink.Devices.HydroAsetekProDevice.RefreshTemperatures()
   at CorsairLink.Devices.HydroAsetekProDevice.Refresh()
   at FanControl.CorsairLink.CorsairLinkPlugin.Refresh()
Data:
    driverStatus: SI_WRITE_ERROR

**Comment by EvanMulawski** [comment]
Hi @Andyden4483, this is being tracked in #89. A user has provided a [workaround](https://github.com/EvanMulawski/FanControl.CorsairLink/issues/89#issuecomment-1712835556) using [DevManView](https://www.nirsoft.net/utils/device_manager_view.html) until it can be fixed in v2.0.
